
export const QTY_SHOPPINGBAG = 'QTY_SHOPPINGBAG'
export const ADD_ITEM = 'ADD_ITEM'
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY'
export const INPUT_SEARCH = 'INPUT_SEARCH'
export const SET_OFFSET = 'SET_OFFSET'
export const SET_ITEMS = 'SET_ITEMS'
export const SET_MORE_ITEMS = 'SET_MORE_ITEMS'
export const SELECT_ALL_CATEGORY ='SELECT_ALL_CATEGORY'